services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot:/var/www/certbot # Let's Encrypt
      - ./nginx/ssl:/etc/letsencrypt:ro # Let's Encrypt
    depends_on:
      - app
    networks:
      - webnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - NODE_ENV=development
    networks:
      - webnet

  certbot: # Let's Encrypt
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - webnet

networks:
  webnet: