name: Deploy to Xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Replace variables in Nginx config
        run: |
          envsubst '${NGINX_HTTP_PORT} ${NGINX_HTTPS_PORT} ${NGINX_WS_PORT} ${NGINX_APP_PORT} ${NGINX_DOMAIN} ${NGINX_WWW_DOMAIN}' < ./nginx/default.template.conf > ./nginx/default.conf
        env:
          NGINX_HTTP_PORT: ${{ secrets.NGINX_HTTP_PORT }}
          NGINX_HTTPS_PORT: ${{ secrets.NGINX_HTTPS_PORT }}
          NGINX_WS_PORT: ${{ secrets.NGINX_WS_PORT }}
          NGINX_APP_PORT: ${{ secrets.NGINX_APP_PORT }}
          NGINX_DOMAIN: ${{ secrets.NGINX_DOMAIN }}
          NGINX_WWW_DOMAIN: ${{ secrets.NGINX_WWW_DOMAIN }}

      - name: Package application
        run: |
          mkdir -p tmp_package
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='manuals' \
            --exclude='private' \
            ./ tmp_package/

          # .envファイルを作成
          cat <<EOF > tmp_package/.env
          PORT=${{ secrets.PORT }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          CLERK_JWT_ENDPOINT=${{ secrets.CLERK_JWT_ENDPOINT }}
          WS_PORT=${{ secrets.WS_PORT }}
          BLOCKED_IP_ADDRESSES=${{ secrets.BLOCKED_IP_ADDRESSES }}
          ENV=${{ secrets.ENV }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          IV_LENGTH=${{ secrets.IV_LENGTH }}
          NGINX_HTTP_PORT=${{ secrets.NGINX_HTTP_PORT }}
          NGINX_HTTPS_PORT=${{ secrets.NGINX_HTTPS_PORT }}
          NGINX_WS_PORT=${{ secrets.NGINX_WS_PORT }}
          NGINX_APP_PORT=${{ secrets.NGINX_APP_PORT }}
          NGINX_DOMAIN=${{ secrets.NGINX_DOMAIN }}
          NGINX_WWW_DOMAIN=${{ secrets.NGINX_WWW_DOMAIN }}
          EOF

          # アーカイブ作成
          tar -czf app.tar.gz -C tmp_package .
          rm -rf tmp_package
      
      - name: Deploy application
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "/home/appuser/projects"

      - name: Restart application with Docker Compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/appuser/projects
            tar -xzf app.tar.gz
            rm -f app.tar.gz
            docker-compose down || true
            docker-compose up -d --build